# Generated by Django 4.1 on 2022-08-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('cod_equipamento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_equipamento', models.CharField(max_length=50)),
                ('marca_equipamneto', models.CharField(max_length=50)),
                ('modelo_equipamneto', models.CharField(max_length=100)),
                ('atendente_equipamento', models.CharField(max_length=100)),
                ('data_chegada', models.DateTimeField(verbose_name='data de chegada')),
                ('solicitacao_equipamento', models.CharField(max_length=250)),
                ('fk_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadClientes.cliente')),
            ],
        ),
    ]
