# Generated by Django 4.1 on 2022-08-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('Código', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('Tipo do equipamento', models.CharField(default='none', max_length=50)),
                ('Marca', models.CharField(default='none', max_length=50)),
                ('Modelo', models.CharField(default='none', max_length=100)),
                ('Atendente/Responsável', models.CharField(default='none', max_length=100)),
                ('Data de chegada', models.DateTimeField(default='2020/10/10 10:00:00', verbose_name='data de chegada')),
                ('Solicitações exigidas', models.CharField(default='none', max_length=250)),
                ('Cliente', models.ForeignKey(default=3654, on_delete=django.db.models.deletion.CASCADE, to='cadClientes.cliente')),
            ],
        ),
    ]
