# Generated by Django 4.1 on 2022-08-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadEquipamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='marca_equipamneto',
            new_name='marca_equipamento',
        ),
        migrations.RenameField(
            model_name='equipamento',
            old_name='modelo_equipamneto',
            new_name='modelo_equipamento',
        ),
    ]
